-- -----------------------------------------------------
-- Insercion de Tickers
-- -----------------------------------------------------

INSERT INTO DF_TICKERS(TICKER, NOMBRE) VALUES ('MMM', '3M Co');
INSERT INTO DF_TICKERS(TICKER, NOMBRE) VALUES ('AXP', 'American Express Co');
INSERT INTO DF_TICKERS(TICKER, NOMBRE) VALUES ('AAPL', 'Apple Inc.');
INSERT INTO DF_TICKERS(TICKER, NOMBRE) VALUES ('BA', 'Boeing Co');
INSERT INTO DF_TICKERS(TICKER, NOMBRE) VALUES ('CAT', 'Caterpillar Inc');
INSERT INTO DF_TICKERS(TICKER, NOMBRE) VALUES ('CVX', 'Chevron Corp');
INSERT INTO DF_TICKERS(TICKER, NOMBRE) VALUES ('CSCO', 'Cisco Systems Inc');
INSERT INTO DF_TICKERS(TICKER, NOMBRE) VALUES ('KO', 'Coca-Cola Co');
INSERT INTO DF_TICKERS(TICKER, NOMBRE) VALUES ('DD', 'E. I. du Pont de Nemours and Company');
INSERT INTO DF_TICKERS(TICKER, NOMBRE) VALUES ('XOM', 'Exxon Mobil Corp');
INSERT INTO DF_TICKERS(TICKER, NOMBRE) VALUES ('GE', 'General Electric Co');
INSERT INTO DF_TICKERS(TICKER, NOMBRE) VALUES ('GS', 'Goldman Sachs Group Inc');
INSERT INTO DF_TICKERS(TICKER, NOMBRE) VALUES ('HD', 'Home Depot Inc');
INSERT INTO DF_TICKERS(TICKER, NOMBRE) VALUES ('INTC', 'Intel Corp');
INSERT INTO DF_TICKERS(TICKER, NOMBRE) VALUES ('IBM', 'Intl Business Machines Corp');
INSERT INTO DF_TICKERS(TICKER, NOMBRE) VALUES ('JNJ', 'Johnson & Johnson');
INSERT INTO DF_TICKERS(TICKER, NOMBRE) VALUES ('JPM', 'JP Morgan Chase & Co');
INSERT INTO DF_TICKERS(TICKER, NOMBRE) VALUES ('MCD', 'McDonald''s Corp');
INSERT INTO DF_TICKERS(TICKER, NOMBRE) VALUES ('MRK', 'Merck & Co Inc');
INSERT INTO DF_TICKERS(TICKER, NOMBRE) VALUES ('MSFT', 'Microsoft Corp');
INSERT INTO DF_TICKERS(TICKER, NOMBRE) VALUES ('NKE', 'NIKE Inc B');
INSERT INTO DF_TICKERS(TICKER, NOMBRE) VALUES ('PFE', 'Pfizer Inc');
INSERT INTO DF_TICKERS(TICKER, NOMBRE) VALUES ('PG', 'Procter & Gamble');
INSERT INTO DF_TICKERS(TICKER, NOMBRE) VALUES ('TRV', 'Travelers Cos Inc');
INSERT INTO DF_TICKERS(TICKER, NOMBRE) VALUES ('UTX', 'United Technologies Corp');
INSERT INTO DF_TICKERS(TICKER, NOMBRE) VALUES ('UNH', 'Unitedhealth Group Inc');
INSERT INTO DF_TICKERS(TICKER, NOMBRE) VALUES ('VZ', 'Verizon Communications Inc');
INSERT INTO DF_TICKERS(TICKER, NOMBRE) VALUES ('V', 'Visa Inc A');
INSERT INTO DF_TICKERS(TICKER, NOMBRE) VALUES ('WMT', 'Wal-Mart Stores');
INSERT INTO DF_TICKERS(TICKER, NOMBRE) VALUES ('DIS', 'Walt Disney Co');



-- -----------------------------------------------------
-- Insercion de Modulos
-- -----------------------------------------------------

INSERT INTO DF_MODULOS(DES_MODULO) VALUES ('scrap_invertia_cortop');
INSERT INTO DF_MODULOS(DES_MODULO) VALUES ('scrap_invertia_mediop');

INSERT INTO DF_MODULOS(DES_MODULO) VALUES ('TARGET');
INSERT INTO DF_MODULOS(DES_MODULO) VALUES ('datos_macro');
INSERT INTO DF_MODULOS(DES_MODULO) VALUES ('datos_bursatiles');

INSERT INTO DF_MODULOS(DES_MODULO) VALUES ('rss_vol');
INSERT INTO DF_MODULOS(DES_MODULO) VALUES ('rss_avg_positive');
INSERT INTO DF_MODULOS(DES_MODULO) VALUES ('rss_avg_negative');
INSERT INTO DF_MODULOS(DES_MODULO) VALUES ('rss_avg_ratio');
INSERT INTO DF_MODULOS(DES_MODULO) VALUES ('rss_avg_anger');
INSERT INTO DF_MODULOS(DES_MODULO) VALUES ('rss_avg_disgust');
INSERT INTO DF_MODULOS(DES_MODULO) VALUES ('rss_avg_fear');
INSERT INTO DF_MODULOS(DES_MODULO) VALUES ('rss_avg_joy');
INSERT INTO DF_MODULOS(DES_MODULO) VALUES ('rss_avg_sadness');
INSERT INTO DF_MODULOS(DES_MODULO) VALUES ('rss_avg_surprise');


INSERT INTO DF_MODULOS(DES_MODULO) VALUES ('sen_polaridad');
INSERT INTO DF_MODULOS(DES_MODULO) VALUES ('sen_porcentaje');
INSERT INTO DF_MODULOS(DES_MODULO) VALUES ('syu_polaridad');
INSERT INTO DF_MODULOS(DES_MODULO) VALUES ('syu_porcentaje');

INSERT INTO DF_MODULOS(DES_MODULO) VALUES ('vol_trends');



-- -----------------------------------------------------
-- Insercion de Origenes RSS
-- -----------------------------------------------------

-- INSERT INTO RSS_ORIGEN (NOMBRE, URL) VALUES ('pistonudos', 'http://www.pistonudos.com/feed/');
-- INSERT INTO RSS_ORIGEN (NOMBRE, URL) VALUES ('engadget', 'http://es.engadget.com/rss.xml');
-- INSERT INTO RSS_ORIGEN (NOMBRE, URL) VALUES ('microsiervos', 'http://www.microsiervos.com/index.rdf');
-- INSERT INTO RSS_ORIGEN (NOMBRE, URL) VALUES ('finofilipino', 'http://feeds.feedburner.com/finofilipino/cdiM');


INSERT INTO RSS_ORIGEN (NOMBRE, URL) VALUES ('USA Today (USA)', 'http://rssfeeds.usatoday.com/usatoday-NewsTopStories');
INSERT INTO RSS_ORIGEN (NOMBRE, URL) VALUES ('CNN (USA)', 'http://rss.cnn.com/rss/money_topstories.rss');
INSERT INTO RSS_ORIGEN (NOMBRE, URL) VALUES ('Wall Street Journal (USA)', 'http://www.wsj.com/news/economy');
INSERT INTO RSS_ORIGEN (NOMBRE, URL) VALUES ('Market Watch (USA)', 'http://www.marketwatch.com/rss/topstories');
INSERT INTO RSS_ORIGEN (NOMBRE, URL) VALUES ('BBC (UK)', 'http://feeds.bbci.co.uk/news/business/economy/rss.xml');
INSERT INTO RSS_ORIGEN (NOMBRE, URL) VALUES ('FOX (USA)', 'http://feeds.foxnews.com/foxnews/latest');
INSERT INTO RSS_ORIGEN (NOMBRE, URL) VALUES ('Business Insider', 'http://feeds2.feedburner.com/businessinsider');
INSERT INTO RSS_ORIGEN (NOMBRE, URL) VALUES ('CNBC (USA)', 'http://www.cnbc.com/id/20910258/device/rss/rss.html');
INSERT INTO RSS_ORIGEN (NOMBRE, URL) VALUES ('The Guardian (UK)', 'http://www.guardian.co.uk/business/useconomy/rss');
INSERT INTO RSS_ORIGEN (NOMBRE, URL) VALUES ('The Economist (USA)', 'http://www.economist.com/topics/us-economy/index.xml');
INSERT INTO RSS_ORIGEN (NOMBRE, URL) VALUES ('Financial Times (USA)', 'http://www.ft.com/rss/world/us/economy');
INSERT INTO RSS_ORIGEN (NOMBRE, URL) VALUES ('New York Times (USA)', 'http://www.nytimes.com/services/xml/rss/nyt/Economy.xml');
INSERT INTO RSS_ORIGEN (NOMBRE, URL) VALUES ('NPR (USA)', 'http://www.npr.org/rss/rss.php?id=1017');
INSERT INTO RSS_ORIGEN (NOMBRE, URL) VALUES ('NPR (USA)', 'http://www.npr.org/rss/rss.php?id=1006');
INSERT INTO RSS_ORIGEN (NOMBRE, URL) VALUES ('NBC (USA)', 'http://feeds.nbcnews.com/feeds/topstories');



-- -----------------------------------------------------
-- Insercion de terminos relacionados para las busquedas
-- -----------------------------------------------------

INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (1, '3M');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (2, 'American Express');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (2, 'Credit Card');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (3, 'Apple');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (3, 'MacOS');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (3, 'Siri');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (3, 'iPhone');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (3, 'iPad');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (4, 'Boeing');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (4, 'Airplane');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (5, 'Caterpillar');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (5, 'Contruction');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (6, 'Chevron');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (7, 'Cisco');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (7, 'Router');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (8, 'Coca-Cola');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (8, 'Pepsi');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (9, 'E. I. du Pont de Nemours and Company');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (10, 'Exxon');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (10, 'Petrol');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (10, 'Gasoline');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (11, 'General Electric');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (12, 'Goldman Sachs');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (13, 'Home Depot');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (13, 'Hardware');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (14, 'Intel');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (14, 'Microprocessor');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (14, 'x86');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (15, 'IBM');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (15, 'Computers');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (16, 'Johnson & Johnson');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (16, 'Shampoo');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (17, 'JP Morgan Chase & Co');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (17, 'Investment');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (18, 'McDonald');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (18, 'Burger');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (18, 'Fast food');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (19, 'Merck & Co');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (20, 'Microsoft');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (20, 'Windows');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (21, 'Nike');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (22, 'Pfizer');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (22, 'Pharmaceutical');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (23, 'Procter & Gamble');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (24, 'Travelers');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (25, 'United Technologies Corp');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (26, 'Unitedhealth Group');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (26, 'Health');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (26, 'Decease');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (26, 'Insurance');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (27, 'Verizon');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (27, 'Cell Phone');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (28, 'Visa');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (28, 'Credit Card');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (28, 'Payment');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (29, 'Wal-Mart');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (29, 'Supermarket');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (30, 'Disney');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (30, 'Cartoons');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (30, 'Pixar');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (30, 'Marvel');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (30, 'Star Wars');
INSERT INTO DF_TERMINOS (ID_TICKER, TERMINO) VALUES (30, 'The Jungle Book');






